### ISSUE TITLE
Error Assertion Failed

### ISSUE THREAD

**Issue by chndranndr** [turtiustrek/taskmanager#12]
![image](https://user-images.githubusercontent.com/9008007/114025808-ba6f2400-989f-11eb-8a7d-3e2797f8f57f.png)
I can get it work the first time I tried it, but after I changed the images in frames directory, it always throws this error. I tried to recompiled the injector, re-clone your repo, no luck

**Comment by turtiustrek** [comment]
This error is indicating a problem with ```config.json``` file. I think i may have added a white space by accident during a commit or the file is not found by the dll. 
For reference here is the functional config.json file 
```
{
  "fake_cpu_count": 1024,
  "block_width": 43,
  "modifed_time":5
}
```
