### ISSUE TITLE
Support for builds 1909 and 20H2

### ISSUE THREAD

**Issue by stopmotio** [turtiustrek/taskmanager#13]
Can anyone verify these work? They are the latest versions. (1909 is there because 20H2 is in a slow rollout, wow microsoft, thanks for the bs)

**Comment by turtiustrek** [comment]
1909 is not supported. only 20H2(19041) is.

**Comment by stopmotio** [comment]
Would supporting 1909 be an unnecessary burden?

**Comment by turtiustrek** [comment]
Pretty much, its the revision where i do not have access too so i cannot say what has changed and what has not.

**Comment by stopmotio** [comment]
Shit, I literally just got the update a week ago.
Closing...
