### ISSUE TITLE
Getting error in task manager console

### ISSUE THREAD

**Issue by MatPrayer** [turtiustrek/taskmanager#2]
After injecting the dll into Task Manager, the first three checks fail. I'm using Windows 19041 build. What could I have done wrong?
![image](https://user-images.githubusercontent.com/61880817/111518840-c2332100-8756-11eb-862c-232ce3e1ef2a.png)

**Comment by turtiustrek** [comment]
your task manager version is 10.0.19041.84 which is from February 11, 2020(slow ring) while the supported one are from the 
Slow ring and release preview builds. 
https://www.wikiwand.com/en/Windows_10_version_history_(version_2004)
if you want, I can add the support in when I can get my hands on the 10.0.19041.84 taskmgr.exe

**Comment by MatPrayer** [comment]
Thank you. I'm going to download the correct build and try again

**Comment by turtiustrek** [comment]
added the update, marked as untested at https://github.com/turtiustrek/taskmanager/commit/ebfce5cba71103e437cd3bd0623e8b9a51721aa1

**Comment by MatPrayer** [comment]
Ok. Thank you very much
