### ISSUE TITLE
One or more functions were not found, attempting alternative table

### ISSUE THREAD

**Issue by xenos1337** [turtiustrek/taskmanager#6]
So, I'm getting One or more functions were not found, attempting alternative table When I'm Injecting it.

![image](https://user-images.githubusercontent.com/66328734/111868731-e3c12200-897b-11eb-9017-33e601cac9fe.png)
I Don't know what I'm doing wrong?? 
That's my winver
![image](https://user-images.githubusercontent.com/66328734/111868752-fb000f80-897b-11eb-8529-dc877a314984.png)

**Comment by turtiustrek** [comment]
Nothing, this version is not supported. Will push it out on the next commit

**Comment by xenos1337** [comment]
Okay thanks.

**Comment by turtiustrek** [comment]
added the new update at this commit https://github.com/turtiustrek/taskmanager/commit/50c2d150956d667be4a6f708d845e9c6bd5e4132

**Comment by xenos1337** [comment]
![image](https://user-images.githubusercontent.com/66328734/114286811-59dc1480-9a62-11eb-8b9f-d4fed07df2d7.png)
Still having the issue after redownloading from the latest update????

**Comment by turtiustrek** [comment]
Apologizes for the close and thanks for the feedback. Can you try this commit https://github.com/turtiustrek/taskmanager/commit/f4420e9974fb258a8d9fb5a06bfa013eb9a08050
It fixes a typo. 
If you do try it and it works please do let me know

**Comment by xenos1337** [comment]
Yes it works now, but is it normal that it's just blinking in random colors? 
![SAfmRyt0Dw](https://user-images.githubusercontent.com/66328734/114738616-6bfed100-9d48-11eb-8a81-f6747c4fdee1.gif)

**Comment by turtiustrek** [comment]
No, that's not supposed to happen. I believe parameters changed, ill take a look.

**Comment by xenos1337** [comment]
Ok, thanks appreciate the work

**Comment by turtiustrek** [comment]
Yes parameters changed, might need a lot of rework to implement this change.
