### ISSUE TITLE
I can't get the grid.

### ISSUE THREAD

**Issue by robloxboy24** [turtiustrek/taskmanager#8]
I followed all the instructions and the .exe works, but when I open the task manager, I don't get the grid as you do.

**Comment by turtiustrek** [comment]
Please send screenshots of the console which has spawned in task manager.

**Comment by robloxboy24** [comment]
It's not the command prompt, it's the task manager; it just goes not show the grid.

**Comment by turtiustrek** [comment]
show me your windows version. 
Execute the following command: ```winver```

**Comment by robloxboy24** [comment]
k

**Comment by robloxboy24** [comment]
![image](https://user-images.githubusercontent.com/71779578/112862539-de528e80-9083-11eb-8a82-3676ca1a1041.png)

**Comment by turtiustrek** [comment]
This application supports only 19041 and 18362. your windows version is 19042.

**Comment by robloxboy24** [comment]
Oh. Okay.
